# Generated by Django 3.0 on 2019-12-13 05:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recibo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerarPagoLuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('MontoUsuario', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto a pagar el usuario')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Agua', verbose_name='Codigo del servicio ')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a pagar')),
            ],
            options={
                'verbose_name': 'GENERAR PAGO DE LUZ',
                'verbose_name_plural': 'GENERAR PAGOS DE LUZ',
            },
        ),
        migrations.CreateModel(
            name='GenerarPagoCuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('MontoUsuario', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto a pagar el usuario')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Agua', verbose_name='Codigo del servicio ')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a pagar')),
            ],
            options={
                'verbose_name': 'GENERAR PAGO DE CUARTO',
                'verbose_name_plural': 'GENERAR PAGOS DE CUARTO',
            },
        ),
        migrations.CreateModel(
            name='GenerarPagoAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('MontoUsuario', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto a pagar el usuario')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Agua', verbose_name='Codigo del servicio ')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a pagar')),
            ],
            options={
                'verbose_name': 'GENERAR PAGO DE AGUA',
                'verbose_name_plural': 'GENERAR PAGOS DE AGUA',
            },
        ),
    ]
