# Generated by Django 3.0 on 2019-12-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recibo', '0001_initial'),
        ('GenerarPago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarpagocuarto',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Cuarto', verbose_name='Codigo del servicio '),
        ),
        migrations.AlterField(
            model_name='generarpagoluz',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Luz', verbose_name='Codigo del servicio '),
        ),
    ]
