# Generated by Django 3.0 on 2019-12-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recibo', '0001_initial'),
        ('GenerarPago', '0002_auto_20191213_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagoagua',
            name='Estado',
            field=models.BooleanField(default=True, verbose_name='PAGAR(Marca la casilla si va confirmar el pago)'),
        ),
        migrations.AddField(
            model_name='generarpagocuarto',
            name='Estado',
            field=models.BooleanField(default=True, verbose_name='PAGAR(Marca la casilla si va confirmar el pago)'),
        ),
        migrations.AddField(
            model_name='generarpagoluz',
            name='Estado',
            field=models.BooleanField(default=True, verbose_name='PAGAR(Marca la casilla si va confirmar el pago)'),
        ),
        migrations.AlterField(
            model_name='generarpagocuarto',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Cuarto', verbose_name='Numero o Codigo del cuarto '),
        ),
    ]
