# Generated by Django 3.0 on 2019-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=8, verbose_name='Codigo del Recibo')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Agua',
                'verbose_name_plural': 'Agua',
                'ordering': ['-Creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=8, verbose_name='Numero o Codigo del Cuarto')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Crecion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de Actualizacion')),
            ],
            options={
                'verbose_name_plural': 'Cuartos',
                'ordering': ['-Creacion'],
            },
        ),
        migrations.CreateModel(
            name='Luz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=8, verbose_name='Codigo del Recibo')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Luz',
                'verbose_name_plural': 'Luz',
                'ordering': ['-Creacion'],
            },
        ),
    ]
