# Generated by Django 3.0 on 2019-12-13 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarPagoLuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Luz', verbose_name='Codigo del servicio ')),
            ],
            options={
                'verbose_name': 'REGISTRAR PAGO DE LUZ',
                'verbose_name_plural': 'REGISTRAR PAGOS DE LUZ',
            },
        ),
        migrations.CreateModel(
            name='RegistrarPagoCuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Cuarto', verbose_name='Codigo del servicio ')),
            ],
            options={
                'verbose_name': 'REGISTRAR PAGO DE CUARTO',
                'verbose_name_plural': 'REGISTRAR PAGOS DE CUARTO',
            },
        ),
        migrations.CreateModel(
            name='RegistrarPagoAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del recibo ')),
                ('Monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto del recibo')),
                ('Creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('Actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recibo.Agua', verbose_name='Codigo del servicio ')),
            ],
            options={
                'verbose_name': 'REGISTRAR PAGO DE AGUA',
                'verbose_name_plural': 'REGISTRAR PAGOS DE AGUA',
            },
        ),
    ]
