# Generated by Django 3.0 on 2019-12-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrarPago', '0002_auto_20191215_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarpagoagua',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='registrarpagocuarto',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='registrarpagoluz',
            name='Estado',
        ),
    ]
